language: php
php:
  - '5.6'
  - '7.0'

before_install:
  - composer install
  - composer dump-autoload

script: php ./vendor/phpunit/phpunit/phpunit

addons:
    code_climate:
        repo_token: 09ae80a14bd9f525997ee392a5391b1e805db2531cf2b74efb9529a76629aebf